### PR TITLE
Drop python 3.8, add 3.12, 3.13 support

### PR DESCRIPTION
**Pull request by ds-cbo**
Updating tests to cover all currently [supported](https://devguide.python.org/versions/) python versions

### CODE REVIEW

**Comment by ds-cbo** [comment]
Ah, python 3.13 is still too far ahead for pyo3 (sub-dependency through cryptography) for now, but it seems to be close to done: https://github.com/PyO3/pyo3/issues/4265

**Review by MasterKale — APPROVED** [review]
@ds-cbo Thank you for taking this work on, this all looks good to me. And thanks for the timeline link 👀

**Comment by MasterKale** [comment]
@ds-cbo These changes have gone out as `webauthn==2.3.0` now available on PyPI https://pypi.org/project/webauthn/2.3.0/

**Comment by ds-cbo** [comment]
@MasterKale Thanks! Happy to help

**Pull request merged**
