### PR TITLE
Add support for multiple acceptable credentials

### PR DESCRIPTION
**Pull request by mdedonno1337**
Add the support for multiple credentials in the WebAuthnAssertionOptions() object.
This allow the user to use any key to login (when multiple keys are registered on the server side, of course).

### CODE REVIEW

**Comment by mdedonno1337** [comment]
wrong email used in the first commit, sorry for the force-push ...

**Comment by futureimperfect** [comment]
Thanks for the PR, @mdedonno1337! I just realized that I responded to #39 before taking a closer look at this PR and I see they're very similar. I like that this one isn't API-breaking, but I see why @woodruffw made the changes to the constructor to accept multiple `webauthn_users`. I'm curious to hear your thoughts on this. Thanks!

**Comment by woodruffw** [comment]
Ah, that's what I get for not checking the open PRs...

**Comment by mdedonno1337** [comment]
I've considered the changes on the constructor with multiples `webauthn_users`. The issue for me is the construction of multiple `webauthn_users` objects, with potentials conflicting information (username, display name, ...) that will not be used anyway. That I've "juste" added the check on the use of the `webauthn_user` object to check if the credentials object is a list or not.

**Comment by futureimperfect** [comment]
As mentioned in #39, I'm going to close this PR. Thanks!

**Pull request closed without merging**
